// packages/extension/transpiler/mdx/rehype-raw.ts
// * rehype plugin to handle raw HTML nodes generated by rehype-katex
// * converts raw HTML to MDX JSX expressions that can be compiled to JavaScript

import { visit } from 'unist-util-visit';
import type { Root } from 'hast';

export default function rehypeRaw() {
  return (tree: Root) => {
    visit(tree, 'raw', (node: any) => {
      // * convert raw HTML node to mdxJsxFlowElement that renders the HTML
      // * this allows the HTML string to be safely compiled by @mdx-js/mdx
      const htmlValue = (node.value || '')
        .replace(/"/g, '\\"')
        .replace(/\n/g, '\\n');

      // * replace raw node w/ a JSX expression
      // * dangerouslySetInnerHTML is required since KaTeX output is trusted
      const jsxNode: {
        type: string;
        name: string;
        attributes: { type: string; value: string }[];
        children: never[];
        position?: typeof node.position;
      } = {
        type: 'mdxJsxFlowElement',
        name: 'div',
        attributes: [
          {
            type: 'mdxJsxAttributeValueExpression',
            value: `{ dangerouslySetInnerHTML: { __html: "${htmlValue}" } }`,
          },
        ],
        children: [],
      };

      // * copy position info for error reporting
      if (node.position) {
        jsxNode.position = node.position;
      }

      Object.assign(node, jsxNode);
    });
  };
}
