// packages/shared/config/index.ts
// re-exports for config-related types & enums

export {
  FRAMEWORK_IDS,
  FRAMEWORK_SETTINGS,
  TAILWIND_ENABLED_VALUES,
  UNKNOWN_BEHAVIOR_VALUES,
  UPDATE_MODE_VALUES,
  SECURITY_POLICY_VALUES,
  type TailwindEnabledValue,
  type UnknownBehaviorValue,
  type UpdateModeValue,
  type SecurityPolicyValue,
} from './enums';

export { MDX_PREVIEW_CONFIG_SCHEMA } from './schema';

export {
  DEFAULT_PREVIEW_UPDATE_MODE,
  DEFAULT_PREVIEW_DEBOUNCE_DELAY_MS,
  DEFAULT_PREVIEW_ENABLE_SCRIPTS,
  DEFAULT_PREVIEW_OPEN_MDX_LINKS_IN_PREVIEW,
  DEFAULT_PREVIEW_SECURITY_POLICY,
  DEFAULT_PREVIEW_USE_VSCODE_MARKDOWN_STYLES,
  DEFAULT_PREVIEW_USE_WHITE_BACKGROUND,
  DEFAULT_PREVIEW_CUSTOM_CSS,
  DEFAULT_PREVIEW_CUSTOM_LAYOUT_PATH,
  DEFAULT_PREVIEW_THEME,
  DEFAULT_CODE_BLOCK_THEME,
  DEFAULT_MERMAID_THEME,
  DEFAULT_AUTO_THEME,
  DEFAULT_USE_SUCRASE_TRANSPILER,
  DEFAULT_TAILWIND_ENABLED,
  DEFAULT_TAILWIND_MAX_FILE_SIZE_BYTES,
  DEFAULT_TAILWIND_MAX_CSS_FILES_TO_SEARCH,
  DEFAULT_TAILWIND_CACHE_MAX_ENTRIES,
  DEFAULT_TAILWIND_CACHE_TTL_SECONDS,
  DEFAULT_TAILWIND_COMPILATION_TIMEOUT_MS,
  DEFAULT_FRAMEWORK,
  DEFAULT_FRAMEWORK_COMPONENT_SHIMS,
  DEFAULT_COMPONENTS_BUILTINS,
  DEFAULT_COMPONENTS_UNKNOWN_BEHAVIOR,
  DEFAULT_WATCHER_DEBOUNCE_MS,
  SETTINGS_DEFAULTS,
} from './defaults';
