// packages/shared/logging/tags.ts
// centralized log tag constants for extension & webview packages

export const LogTags = {
  // rpc & communication
  RPC_EXT: 'RPC-EXT',
  RPC_WEBVIEW: 'RPC-WEBVIEW',
  EXT_HANDLE: 'EXT-HANDLE',

  // preview system
  PREVIEW: 'PREVIEW',
  PREVIEW_MANAGER: 'PREVIEW-MANAGER',
  PREVIEW_EVALUATOR: 'PREVIEW-EVALUATOR',
  PREVIEW_CONTEXT: 'PREVIEW-CONTEXT',
  EVALUATE: 'EVALUATE',
  ENGINE: 'ENGINE',
  WEBVIEW_MGR: 'WEBVIEW-MGR',

  // module system
  UNIFIED_RESOLVER: 'UNIFIED-RESOLVER',
  ENHANCED_RESOLVE: 'ENHANCED-RESOLVE',
  FILE_PROBE: 'FILE-PROBE',
  TYPESCRIPT: 'TYPESCRIPT',
  RESOLVER: 'RESOLVER',
  RESOLVER_SUBSYSTEM: 'RESOLVER-SUBSYSTEM',
  CACHE_SUBSYSTEM: 'CACHE-SUBSYSTEM',
  MODULE_SYSTEM: 'MODULE-SYSTEM',
  IMPORT_EXTRACTOR: 'IMPORT-EXTRACTOR',

  // compilation
  COMPILE: 'COMPILE',
  BABEL: 'BABEL',
  COMPONENT_MAPPER: 'COMPONENT-MAPPER',

  // file handlers
  SASS_HANDLER: 'SASS-HANDLER',

  // watchers
  WATCHER: 'WATCHER',
  WATCHER_MANAGER: 'WATCHER-MANAGER',
  DEP_WATCHER: 'DEP-WATCHER',
  DOC_TRACKER: 'DOC-TRACKER',
  CSS: 'CSS',
  TAILWIND_WATCHER: 'TAILWIND-WATCHER',
  PKG_JSON: 'PKG-JSON',

  // tailwind
  TAILWIND: 'TAILWIND',
  TAILWIND_SCAN: 'TAILWIND-SCAN',

  // configuration
  CONFIG: 'CONFIG',
  CONFIG_CACHE: 'CONFIG-CACHE',
  CONFIG_MANAGER: 'CONFIG-MANAGER',
  CONFIG_SUBSCRIPTION: 'CONFIG-SUBSCRIPTION',
  TS_CONFIG: 'TS-CONFIG',

  // framework
  FRAMEWORK: 'FRAMEWORK',
  NEXTRA_META: 'NEXTRA-META',
  NEXTRA_CONTEXT: 'NEXTRA-CONTEXT',

  // diagnostics
  COMPONENT_CODE_ACTIONS: 'COMPONENT-CODE-ACTIONS',
  COMPONENT_DETECTOR: 'COMPONENT-DETECTOR',
  COMPONENT_DIAGNOSTICS: 'COMPONENT-DIAGNOSTICS',

  // services
  SERVICE_REGISTRY: 'SERVICE-REGISTRY',
  ERROR_REPORTER: 'ERROR-REPORTER',
  TRUST_MANAGER: 'TRUST-MANAGER',

  // commands & activation
  WORKSPACE: 'WORKSPACE',
  ACTIVATE: 'ACTIVATE',
  PREWARM: 'PREWARM',
  CMD: 'CMD',
  COMMANDS: 'COMMANDS',
  THEME: 'THEME',
  THEME_MANAGER: 'THEME-MANAGER',
  STATUS_BAR: 'STATUS-BAR',

  // file utils
  FILE: 'FILE',
  LOGGING: 'LOGGING',

  // webview package
  APP: 'APP',
  WEBVIEW: 'WEBVIEW',
  RESOURCE_LOADER: 'RESOURCE-LOADER',
  WEBVIEW_STATE: 'WEBVIEW-STATE',
  PRELOAD: 'PRELOAD',
  SHIM_LOADER: 'SHIM-LOADER',
  LOADING_CONTEXT: 'LOADING-CONTEXT',
  TRUST_CONTEXT: 'TRUST-CONTEXT',
  MERMAID_RENDERER: 'MERMAID-RENDERER',
} as const;

export type LogTag = (typeof LogTags)[keyof typeof LogTags];
