// packages/webview-client/src/features/preview/safe/security/allowlist.ts
// DOMPurify allowlist configuration for Safe Mode HTML sanitization

import type { Config } from 'dompurify';

// DOMPurify configuration for safe rendering (only safe HTML elements & attributes)
export const DOMPURIFY_CONFIG: Config = {
  ALLOWED_TAGS: [
    // headings
    'h1',
    'h2',
    'h3',
    'h4',
    'h5',
    'h6',
    // text content
    'p',
    'span',
    'div',
    'br',
    'hr',
    // lists
    'ul',
    'ol',
    'li',
    // text formatting
    'strong',
    'b',
    'em',
    'i',
    'u',
    's',
    'strike',
    'del',
    'ins',
    'mark',
    'sub',
    'sup',
    'small',
    // code
    'pre',
    'code',
    'kbd',
    'samp',
    'var',
    // links & media
    'a',
    'img',
    // quotes & citations
    'blockquote',
    'q',
    'cite',
    'abbr',
    // tables
    'table',
    'thead',
    'tbody',
    'tfoot',
    'tr',
    'th',
    'td',
    'caption',
    'colgroup',
    'col',
    // definition lists
    'dl',
    'dt',
    'dd',
    // other
    'details',
    'summary',
    'figure',
    'figcaption',
    // KaTeX math elements
    'math',
    'semantics',
    'mrow',
    'mi',
    'mo',
    'mn',
    'msup',
    'msub',
    'msubsup',
    'mfrac',
    'mover',
    'munder',
    'munderover',
    'mtable',
    'mtr',
    'mtd',
    'msqrt',
    'mroot',
    'mtext',
    'mspace',
    'annotation',
    'menclose',
    'mphantom',
    'mpadded',
    'mglyph',
    'mlabeledtr',
    'mmultiscripts',
    'mprescripts',
    'none',
    // SVG elements for Mermaid diagrams (no foreignObject for security)
    'svg',
    'g',
    'path',
    'rect',
    'circle',
    'ellipse',
    'line',
    'polyline',
    'polygon',
    'text',
    'tspan',
    'textPath',
    'defs',
    'clipPath',
    'mask',
    'marker',
    'use',
    'symbol',
    'linearGradient',
    'radialGradient',
    'stop',
    'pattern',
    'switch',
    'desc',
    'title',
    'metadata',
  ],
  ALLOWED_ATTR: [
    'href',
    'src',
    'alt',
    'title',
    'class',
    'id',
    'name',
    'target',
    'rel',
    'width',
    'height',
    'colspan',
    'rowspan',
    'scope',
    'loading',
    'decoding',
    // KaTeX math attributes
    'mathvariant',
    'encoding',
    'stretchy',
    'fence',
    'lspace',
    'rspace',
    'columnalign',
    'rowalign',
    'columnspacing',
    'rowspacing',
    'displaystyle',
    'scriptlevel',
    'xmlns',
    'accent',
    'accentunder',
    'notation',
    'separator',
    'movablelimits',
    'symmetric',
    'maxsize',
    'minsize',
    'largeop',
    'form',
    'linethickness',
    'numalign',
    'denomalign',
    'bevelled',
    // KaTeX uses inline styles for sizing/positioning
    'style',
    // SVG attributes for Mermaid diagrams
    'd',
    'fill',
    'stroke',
    'stroke-width',
    'stroke-linecap',
    'stroke-linejoin',
    'stroke-dasharray',
    'stroke-dashoffset',
    'stroke-opacity',
    'fill-opacity',
    'fill-rule',
    'transform',
    'viewBox',
    'x',
    'y',
    'x1',
    'y1',
    'x2',
    'y2',
    'cx',
    'cy',
    'r',
    'rx',
    'ry',
    'points',
    'dx',
    'dy',
    'text-anchor',
    'dominant-baseline',
    'font-size',
    'font-family',
    'font-weight',
    'opacity',
    'clip-path',
    'marker-end',
    'marker-start',
    'marker-mid',
    'gradientUnits',
    'spreadMethod',
    'offset',
    'stop-color',
    'stop-opacity',
    'patternUnits',
    'patternContentUnits',
    'preserveAspectRatio',
    'xlink:href',
    'xmlns:xlink',
    'version',
    'role',
    'aria-label',
    // Mermaid data attributes
    'data-mermaid-chart',
    'data-mermaid-id',
    // PlantUML data attributes
    'data-plantuml-code',
    'data-plantuml-id',
    // Graphviz data attributes
    'data-graphviz-code',
    'data-graphviz-id',
    'data-graphviz-language',
    // admonition data attributes
    'data-admonition-type',
    // source mapping for preview hover highlighting
    'data-source-line',
  ],
  ADD_ATTR: ['target', 'rel'],
  ALLOW_UNKNOWN_PROTOCOLS: false,
  ALLOWED_URI_REGEXP:
    /^(?:(?:https?|mailto|tel):|[^a-z]|[a-z+.-]+(?:[^a-z+.\-:]|$))/i,
};
